% clear all;
close all;

%% Import of data generated by Python simulation
Goodput1_simulated=table2array(Goodput1)';
Goodput2_simulated=table2array(Goodput2)';
Goodput3_simulated=table2array(Goodput3)';
Goodput4_simulated=table2array(Goodput4)';

l=[10,  15,  20,  25,  30, 35, 40, 45, 50];

l_theo=10:1:50

lambda=900;
% l=10;
c=35;
header_duration=0.233472;
payload_duration=0.102400;
transceiver_wait = 0.006472;

Devices=80000;
 
for i=1:length(l_theo)
   number_nodes=Devices/8;

   [Ps1_theor(i),...
          Goodput1_theor(i)] = theoretical_DR(number_nodes, 1, header_duration, 5/6, payload_duration, transceiver_wait, c, l_theo(i), lambda);

   [Ps2_theor(i),...
          Goodput2_theor(i)] = theoretical_DR(number_nodes, 2, header_duration, 2/3, payload_duration, transceiver_wait, c, l_theo(i), lambda);

   [Ps3_theor(i),...
          Goodput3_theor(i)] = theoretical_DR(number_nodes, 2, header_duration, 1/2, payload_duration, transceiver_wait, c, l_theo(i), lambda);

   [Ps4_theor(i),...
          Goodput4_theor(i)] = theoretical_DR(number_nodes, 3, header_duration, 1/3, payload_duration, transceiver_wait, c, l_theo(i), lambda);

   l_theo(i)
end

%% Figure 1

%%
figure (1);

h=plot(l, smooth(l, Goodput1_simulated/3600), 'o-', 'Color', [0 0.4470 0.7410], 'MarkerFaceColor', [0 0.4470 0.7410], 'LineWidth', 1.5, 'MarkerSize',8);
hold on;
grid on;
% plot(l_theo, Goodput1_theor, '-', 'Color', [0 0.4470 0.7410], 'MarkerFaceColor', [0 0.4470 0.7410], 'LineWidth', 1.5, 'MarkerSize',8);
plot(l, Goodput2_simulated/3600, 's-', 'Color', [0.8500 0.3250 0.0980], 'MarkerFaceColor', [0.8500 0.3250 0.0980], 'LineWidth', 1.5, 'MarkerSize',8);
% plot(l_theo, Goodput2_theor, '-', 'Color', [0.8500 0.3250 0.0980], 'MarkerFaceColor', [0 0.4470 0.7410], 'LineWidth', 1.5, 'MarkerSize',8);
plot(l, Goodput3_simulated/3600, 'd-', 'Color', [0.9290 0.6940 0.1250], 'MarkerFaceColor', [0.9290 0.6940 0.1250], 'LineWidth', 1.5, 'MarkerSize',8);
% plot(l_theo, Goodput3_theor, '-', 'Color', [0.9290 0.6940 0.1250], 'MarkerFaceColor', [0.9290 0.6940 0.1250], 'LineWidth', 1.5, 'MarkerSize',8);
plot(l, Goodput4_simulated/3600, '^-', 'Color', [0.4940 0.1840 0.5560], 'MarkerFaceColor', [0.4940 0.1840 0.5560], 'LineWidth', 1.5, 'MarkerSize',8);
% plot(l_theo, Goodput4_theor, '-', 'Color', [0.4940 0.1840 0.5560], 'MarkerFaceColor', [0.4940 0.1840 0.5560], 'LineWidth', 1.5, 'MarkerSize',8);

clear plot_legend;

plot_legend(1) = plot(inf, inf, 'o', 'Color', [0 0.4470 0.7410], 'MarkerFaceColor', [0 0.4470 0.7410], 'MarkerSize',8);
plot_legend(2) = plot(inf, inf, 's', 'Color', [0.8500 0.3250 0.0980], 'MarkerFaceColor', [0.8500 0.3250 0.0980], 'MarkerSize',8);
plot_legend(3) = plot(inf, inf, 'd', 'Color', [0.9290 0.6940 0.1250], 'MarkerFaceColor', [0.9290 0.6940 0.1250], 'MarkerSize',8);
plot_legend(4) = plot(inf, inf, '^', 'Color', [0.4940 0.1840 0.5560], 'MarkerFaceColor', [0.4940 0.1840 0.5560], 'MarkerSize',8);
plot_legend(5) = plot(inf, inf, '-', 'Color', 'k');

l1 = legend(plot_legend, 'h:1 - CR:5/6', 'h:2 - CR:2/3', 'h:2 - CR:1/2', 'h:3 - CR:1/3', 'Teórico','Fontsize',11);

grid on;
ylabel('$\mathrm{Goodput}$','Interpreter','LaTeX','Fontsize',13);
xlabel('$\mathrm{Carga\,Util}\,{(l)}$','Interpreter','LaTeX','Fontsize',13);

ax = ancestor(h, 'axes')
ax.XAxis.Exponent = 0
ax.XAxis.TickLabelFormat = '%.0f'