close all;

%% Import of data generated by Python simulation
Goodput1_simulated=table2array(Goodput1)';
Goodput2_simulated=table2array(Goodput2)';
Goodput3_simulated=table2array(Goodput3)';
Goodput4_simulated=table2array(Goodput4)';

AoI1_simulated=table2array(AoI1)';
AoI2_simulated=table2array(AoI2)';
AoI3_simulated=table2array(AoI3)';
AoI4_simulated=table2array(AoI4)';

Devices=[1000, 11640, 22280, 32928, 43568, 54208, 64856, 75496, 86136, 96784, 107424, ...
    118064, 128712, 139352, 150000];

%Configuração 1 -> h:1 - CR:5/6
%Configuração 2 -> h:2 - CR:2/3
%Configuração 3 -> h:2 - CR:1/2
%Configuração 4 -> h:3 - CR:1/3


figure; hold on;

plot(Goodput1_simulated/3600, AoI1_simulated, 'o-');
plot(Goodput2_simulated/3600, AoI2_simulated, 's-');
plot(Goodput3_simulated/3600, AoI3_simulated, 'd-');
plot(Goodput4_simulated/3600, AoI4_simulated, '*-');

xlabel('Goodput');
ylabel('AoI');
title('Trade-off entre Goodput e AoI');
legend('h:1 - CR:5/6', 'h:2 - CR:2/3', 'h:2 - CR:1/2', 'h:3 - CR:1/3', 'Teórico','Fontsize',11);
grid on;