% clear all;
close all;

%% Import of data generated by Python simulation
AoI1_simulated=table2array(AoI1)';
AoI2_simulated=table2array(AoI2)';
AoI3_simulated=table2array(AoI3)';
AoI4_simulated=table2array(AoI4)';

l=[10, 20, 30, 40, 50];
%% Figure 1

%%
figure (1);

h=plot(l, AoI1_simulated(1:2:end), 'o-', 'Color', [0 0.4470 0.7410], 'MarkerFaceColor', [0 0.4470 0.7410], 'LineWidth', 1.5, 'MarkerSize',8);
hold on;
grid on;
plot(l, AoI2_simulated(1:2:end), 's-', 'Color', [0.8500 0.3250 0.0980], 'MarkerFaceColor', [0.8500 0.3250 0.0980], 'LineWidth', 1.5, 'MarkerSize',8);
plot(l, AoI3_simulated(1:2:end), 'd-', 'Color', [0.9290 0.6940 0.1250], 'MarkerFaceColor', [0.9290 0.6940 0.1250], 'LineWidth', 1.5, 'MarkerSize',8);
plot(l, AoI4_simulated(1:2:end), '^-', 'Color', [0.4940 0.1840 0.5560], 'MarkerFaceColor', [0.4940 0.1840 0.5560], 'LineWidth', 1.5, 'MarkerSize',8);

clear plot_legend;

plot_legend(1) = plot(inf, inf, 'o', 'Color', [0 0.4470 0.7410], 'MarkerFaceColor', [0 0.4470 0.7410], 'MarkerSize',8);
plot_legend(2) = plot(inf, inf, 's', 'Color', [0.8500 0.3250 0.0980], 'MarkerFaceColor', [0.8500 0.3250 0.0980], 'MarkerSize',8);
plot_legend(3) = plot(inf, inf, 'd', 'Color', [0.9290 0.6940 0.1250], 'MarkerFaceColor', [0.9290 0.6940 0.1250], 'MarkerSize',8);
plot_legend(4) = plot(inf, inf, '^', 'Color', [0.4940 0.1840 0.5560], 'MarkerFaceColor', [0.4940 0.1840 0.5560], 'MarkerSize',8);

l1 = legend(plot_legend, 'h:1 - CR:5/6', 'h:2 - CR:2/3', 'h:2 - CR:1/2', 'h:3 - CR:1/3','Fontsize',11);

grid on;
ylabel('$\mathrm{AoI}$','Interpreter','LaTeX','Fontsize',13);
xlabel('$\mathrm{Intervalo\,de\,Pacotes}\,{(\lambda)}$','Interpreter','LaTeX','Fontsize',13);

ax = ancestor(h, 'axes')
ax.XAxis.Exponent = 0
ax.XAxis.TickLabelFormat = '%.0f'
